#server:
#  port: 8080
#
#spring:
#  application:
#    name: sc-gateway-server
#  cloud:
#    gateway:
#      routes:
#        - id: 测试服务
#          uri: http://192.168.7.153:8088
#          predicates:
#            - Path=/test-service/**
##  cloud:
##    gateway:
##      default-filters:
##      #配置全局swagger 请求头设置过滤器
##      - SwaggerHeaderFilter
##      discovery:
##        locator:
##          #是否与服务发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
##          enabled: false
##          #使用小写的服务id
##          lower-case-service-id: true
#
#GatewayConfig:
#  standAlone: true
#
#
#
###开启端点
##management:
##  endpoints:
##    web:
##      exposure:
##        include: '*'
#
##eureka:
##  client:
##    service-url:
##      defaultZone: http://192.168.1.240:8000/eureka/
#
#logging:
#  level:
#    org.springframework.cloud.gateway: debug